docs/patterns/single-new-eks-observability-accelerators/single-new-eks-native-observability.md

Small wording improvement

---

.eslintrc.js
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci.yaml
Makefile
docs/patterns/single-new-eks-observability-accelerators/single-new-eks-opensource-observability.md
lib/single-new-eks-opensource-observability-construct/grafanaoperatorsecretaddon.ts
lib/single-new-eks-opensource-observability-construct/index.ts
package.json

Adding GH Actions and fixing linter

---

docs/patterns/single-new-eks-observability-accelerators/single-new-eks-opensource-observability.md

fixing readmes

---

README.md
docs/patterns/single-new-eks-observability-accelerators/single-new-eks-native-observability.md

Adding ReadMe Diagrams

---

docs/patterns/single-new-eks-observability-accelerators/single-new-eks-opensource-observability.md

updated secrets manager command in `single-new-eks-opensource-observability.md` file

Updated secrets manager command in doc

---

cdk.json
lib/single-new-eks-opensource-observability-construct/index.ts

*Description of changes:* fixes the dashboard urls

fix dashboards

---

cdk.json

updated cdk json with default-main.js and context

fixed cdk.json

---

bin/single-new-eks-cluster.ts
docs/patterns/single-new-eks-observability-accelerators/single-new-eks-cluster.md
lib/single-new-eks-cluster-construct/index.ts

Single New Eks Cluster

---

README.md

Correct the missing hyperlink on README

---

README.md

#19
Added setup instructions for Ubuntu. Verified on Ubuntu 22.04.2 LTS

Added setup instructions for Linux-ubuntu

---

README.md

updated the readme.md to list new patterns

---

docs/patterns/single-new-eks-observability-accelerators/single-new-eks-opensource-observability.md
lib/single-new-eks-opensource-observability-construct/grafanaoperatorsecretaddon.ts

Integrate AWS SSM Parameter store for storing  AMG API Key

---

cdk.json
lib/common/observability-builder.ts

Fixing QS ID

---

docs/patterns/existing-eks-observability-accelerators/existing-eks-opensource-observability.md
mkdocs.yml

Add documentation for Existing EKS Cluster Open Source Obsrvability

---

mkdocs.yml

Fixing mkdocs logo and favicon path.

fixing logo path

---

docs/tracing.md
mkdocs.yml

*Issue #, if available:* 83
https://github.com/aws-observability/cdk-aws-observability-accelerator/issues/83
borrowed tracing.md from terraform observability accelerator and modified url to point to cdk accelerator page. 
Reorganized folder patterns

Reorganize patterns and add tracing with updated links

---

cdk.json
ci/buildspec.yml

CI Action Fix

---

.github/workflows/e2e.yaml

CI Pipeline Text

---

.github/workflows/e2e.yaml
mkdocs.yml

CI Fixes for Other Issues with mkdocs

---

lib/single-new-eks-cluster-pattern/index.ts
mkdocs.yml

Adding Doc change for nginx mon

---

mkdocs.yml

Update mkdocs.yml for OSS GPU

---

package.json

1.2.0 Release Version

---

mkdocs.yml

Issue-114-MonitorAdotCollector Health check and Monitoring
Issue-114-MonitorAdotCollector Health check and Monitoring
Mkdocs update

Issue-114-MonitorAdotCollector Health check and Monitoring

---

README.md
docs/patterns/existing-eks-observability-accelerators/existing-eks-awsnative-observability.md
docs/patterns/single-new-eks-observability-accelerators/single-new-eks-awsnative-observability.md
lib/existing-eks-awsnative-observability-pattern/index.ts
lib/single-new-eks-awsnative-observability-pattern/index.ts
package.json

Upgrade Packages

---

.github/workflows/e2e.yaml
ci/buildspec.yml

Upgrade GHActions

---

README.md

Fixing ReadMe for Web Publishing

---

.devcontainer/devcontainer.json
.devcontainer/postCreateCommand.sh
README.md

Introducing Dev Containers to Framework

Introducing Dev Containers to Framework

---

mkdocs.yml

Cost Mon Doc Fix Errors.

---

README.md

Adding Badges

---

.github/workflows/markdown-link-check.yaml
README.md
package.json

Release Prep to Next Version of CDK Observability Accelerator

Release Prep to Next Version of CDK Observability Accelerator

---

.github/workflows/ci.yaml
cdk.json
docs/patterns/existing-eks-observability-accelerators/existing-eks-adotmetrics-collection-observability.md
docs/patterns/existing-eks-observability-accelerators/existing-eks-apiserver-observability.md
docs/patterns/existing-eks-observability-accelerators/existing-eks-nginx-observability.md
docs/patterns/existing-eks-observability-accelerators/existing-eks-opensource-observability.md
docs/patterns/single-new-eks-observability-accelerators/single-new-eks-adotmetrics-collection-opensource-observability.md
docs/patterns/single-new-eks-observability-accelerators/single-new-eks-apiserver-opensource-observability.md
docs/patterns/single-new-eks-observability-accelerators/single-new-eks-container-logs-opensource-observability.md
docs/patterns/single-new-eks-observability-accelerators/single-new-eks-gpu-opensource-observability.md
docs/patterns/single-new-eks-observability-accelerators/single-new-eks-graviton-opensource-observability.md
docs/patterns/single-new-eks-observability-accelerators/single-new-eks-inferentia-opensource-observability.md
docs/patterns/single-new-eks-observability-accelerators/single-new-eks-istio-opensource-observability.md
docs/patterns/single-new-eks-observability-accelerators/single-new-eks-java-opensource-observability.md
docs/patterns/single-new-eks-observability-accelerators/single-new-eks-nginx-opensource-observability.md
docs/patterns/single-new-eks-observability-accelerators/single-new-eks-opensource-observability.md
lib/common/resources/otel-collector-config.yml
lib/multi-acc-new-eks-mixed-observability-pattern/argocd-addon-config.ts
lib/multi-acc-new-eks-mixed-observability-pattern/pipeline.ts
package.json

*Issue #176
*Description of changes:* Added two jobs to scrape metrics from new EKS endpoints.

Added new scraper jobs for KSH and KCM Metrics
